export const CATEGORIES_TYPE = {
    FETCH_CATEGORIES_START: 'category/FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'category/FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_ERROR: 'category/FETCH_CATEGORIES_ERROR',
}